### ISSUE TITLE
Long awaiting on search actions

### ISSUE THREAD

**Issue by meysampg** [FreeFeed/freefeed-server#264] opened 2017-11-28 16:31 UTC
On browsing my page or all other pages, FF act very quickly and all things are OK (for my page the mean time loading value is 700ms), but when I wanna search some thing, the loading time grows very bad! For example on searching keyword "meysam" it's about 14000ms!

Did you have similar problem?

**Comment by indeyets** [comment] 2017-11-28 17:44
@meysampg I don't get any results for this word at all (probably private posts?)

Anyway, the search with quotes is supposed to be slow right now. That's a technological limitation we can't deal with right now.

I'm not closing the bug, as the issue is real, but there are no immediate plans on fixing this

**Comment by dsumin** [comment] 2020-06-10 17:38
The new search version resolves this issue.

**Closed as completed by dsumin** 2020-06-10 17:38 UTC
