### ISSUE TITLE
Posts in timeline aren't sorted by activity time

### ISSUE THREAD

**Issue by n1313** [FreeFeed/freefeed-server#7] opened 2015-10-07 15:21 UTC
Some posts on the second page of home feed (home?offset=30) belong to the first page, and some of the posts on the second page appear to be incorrectly sorted.

Proofpic: https://files.slack.com/files-pri/T0457H4G5-F0C1H6VLK/screen_shot_2015-10-07_at_21.33.33.png

**Comment by berkus** [comment] 2016-03-16 09:04
Duplicate of https://dev.freefeed.net/T1

**Closed as completed by berkus** 2016-03-16 09:04 UTC
